# Generated by Django 4.2.20 on 2025-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='barangay',
            field=models.CharField(default='tmp', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Naga City', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='house_num',
            field=models.CharField(default='tmp', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='municipality',
            field=models.CharField(default='tmp', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(default='Camarines Sur', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
