# Generated by Django 4.2.20 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_list', '0002_client_barangay_client_city_client_house_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_num',
            field=models.CharField(default='tmp', max_length=15),
        ),
    ]
