# Generated by Django 4.2.20 on 2025-04-24 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_list', '0006_payment_disbursement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='notes',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
