# Generated by Django 4.2.20 on 2025-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_list', '0007_rename_date_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(default='business', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='municipality',
            field=models.CharField(max_length=100),
        ),
    ]
