# Generated by Django 4.2.20 on 2025-04-24 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_list', '0008_client_occupation_alter_client_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_applied',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='starting_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
